service: youtube-lambda

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2 # or your preferred region
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - GET
        - OPTIONS
        - POST

  environment:
    OC_PUBLIC: ${env:OC_PUBLIC}
    IDENTITY_PRIVATE: ${env:IDENTITY_PRIVATE}
    IC_HOST: ${env:IC_HOST}
    STORAGE_INDEX_CANISTER: ${env:STORAGE_INDEX_CANISTER}
    YOUTUBE_API_KEY: ${env:YOUTUBE_API_KEY}
    FIREBASE_SERVICE_ACCOUNT_JSON: ${env:FIREBASE_SERVICE_ACCOUNT_JSON}
    FIREBASE_COLLECTION: ${env:FIREBASE_COLLECTION}
    PG_CONNECTION: ${env:PG_CONNECTION}

functions:
  botDefinition:
    handler: src/definition.definition
    events:
      - httpApi:
          path: /bot_definition
          method: get

  executeCommand:
    handler: src/execute.command
    events:
      - httpApi:
          path: /execute_command
          method: post

  notify:
    handler: src/notify.notify
    events:
      - httpApi:
          path: /notify
          method: post

  migrate:
    handler: src/migrate.migrate
    events:
      - httpApi:
          path: /migrate
          method: get

  poll:
    handler: src/poll.poll
    events:
      - httpApi:
          path: /poll
          method: get
      - schedule:
          rate: rate(10 minutes)

plugins:

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    platform: node
